---
# Role: Powerline (nass600.powerline)
# ----------------------------------------------------

vundle_user: "{{ user }}"

# Role: Powerline (nass600.powerline)
# ----------------------------------------------------

powerline_config_shell_colorscheme: "purple"
powerline_config_shell_theme: "default_leftonly"
powerline_daemon_destination: "~/.bash_profile"

# Role: Apt (Stouts.apt)
# ----------------------------------------------------

apt_repositories:
  - ppa:ondrej/php
apt_default_packages:
  - unzip


# Role: Git (geerlingguy.git)
# ----------------------------------------------------

git_install_from_source: true
git_install_path: "/usr"
git_version: "2.11.0"


# Role: Dotfiles (geerlingguy.dotfiles)
# ----------------------------------------------------

dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_files:
  - .bash_profile
  - .bash_aliases
  - .config
  - .gitignore
  - .gitconfig
  - .vimrc


# Role: PHP (geerlinguy.php)
# ----------------------------------------------------

php_version: "7.0.15"
php_enable_php_fpm: true
php_webserver_daemon: "nginx"

php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php7.0-gd
  - php7.0-curl
  - php7.0-imap
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - php7.0-mbstring
  - php-sqlite3
  - php-apcu
  - php7.0-pgsql


# Role: PHP Xdebug (geerlinguy.php-xdebug)
# ----------------------------------------------------

php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: 'phpstorm.xdebug'
php_xdebug_module_path: '/usr/lib/php'

# Role: Composer (geerlinguy.composer)
# ----------------------------------------------------

composer_home_path: "{{ home }}/.composer"
composer_home_owner: "{{ user }}"
composer_home_group: "{{ user }}"
composer_global_packages:
  - { name: consolidation/robo, release: "1.0.5" }


# Role: Nginx (jdauphant.nginx)
# ----------------------------------------------------

nginx_user: "{{ user }}"


# Role: Nodejs (geerlingguy.nodejs)
# ----------------------------------------------------

nodejs_version: "6.x"
nodejs_install_npm_user: "{{ user }}"
nodejs_npm_global_packages:
  - name: grunt-cli
    version: 1.2.0
  - name: bower
    version: 1.8.0


## Role: PostgreSQL (geerlingguy.postgresql)
## ----------------------------------------------------

postgresql_version: 9.3.5
postgresql_users:
  - name: root
    password: "root"
    role_attr_flags: "CREATEDB"
