---
# Role: Powerline (nass600.powerline)
# ----------------------------------------------------

vundle_user: "{{ user }}"

# Role: Powerline (nass600.powerline)
# ----------------------------------------------------

powerline_config_shell_colorscheme: "purple"
powerline_config_shell_theme: "default_leftonly"
powerline_daemon_destination: "~/.bash_profile"

# Role: Apt (Stouts.apt)
# ----------------------------------------------------

apt_repositories:
  - ppa:ondrej/php
apt_default_packages:
  - unzip
  - htop
  - python-setuptools
  - vim-nox-py2


# Role: Git (geerlingguy.git)
# ----------------------------------------------------

git_install_from_source: false
git_install_path: "/usr"
git_version: "2.15.0"


# Role: Dotfiles (geerlingguy.dotfiles)
# ----------------------------------------------------

dotfiles_repo: "https://github.com/nass600/dotfiles.git"
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_files:
  - .bash_profile
  - .bash_aliases
  - .config
  - .gitignore
  - .gitconfig
  - .vimrc
  - .dir_colors


# Role: PHP (geerlinguy.php)
# ----------------------------------------------------

php_enable_php_fpm: true
php_webserver_daemon: "nginx"
php_fpm_daemon: "php7.2-fpm"

php_packages:
  - php7.2-common
  - php7.2-cli
  - php7.2-dev
  - php7.2-fpm
  - libpcre3-dev
  - php7.2-gd
  - php7.2-curl
  - php7.2-imap
  - php7.2-json
  - php7.2-opcache
  - php7.2-xml
  - php7.2-mbstring
  - php-sqlite3
  - php-apcu
  - php7.2-mysql
  - php7.2-pgsql
  - php7.2-imagick


# Role: PHP Xdebug (geerlinguy.php-xdebug)
# ----------------------------------------------------

php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: 'phpstorm.xdebug'
php_xdebug_module_path: '/usr/lib/php'
php_xdebug_version: 2.6.0

# Role: Composer (geerlinguy.composer)
# ----------------------------------------------------

composer_home_path: "{{ home }}/.composer"
composer_home_owner: "{{ user }}"
composer_home_group: "{{ user }}"
composer_global_packages:
  - {name: consolidation/robo, release: "1.2.1"}


# Role: Nginx (jdauphant.nginx)
# ----------------------------------------------------

nginx_user: "{{ user }}"


# Role: Nodejs (geerlingguy.nodejs)
# ----------------------------------------------------

nodejs_version: "8.x"
nodejs_install_npm_user: "{{ user }}"


## Role: PostgreSQL (geerlingguy.postgresql)
## ----------------------------------------------------

postgresql_version: 9.3
postgresql_users:
  - name: root
    password: "root"
    role_attr_flags: "SUPERUSER"

postgresql_hba_entries:
  - { type: host, database: all, user: all, address: "0.0.0.0/0", auth_method: trust }

postgresql_global_config_options:
  - option: listen_addresses
    value: "*"
