---
- hosts: all
  become: true
  vars:
    user: ubuntu
    home: "/home/{{ user }}"
    become_user: "{{ user }}"
  roles:
    - geerlingguy.git
    - dotfiles
    - mikegleasonjr.swap
    - jdauphant.nginx
    - geerlingguy.php
    - geerlingguy.composer
#    - setup
#    - git
#    - dotfiles
#    - nginx
#    - mysql
#    - sqlite
#    - mongo
#    - php5
#    - composer
#    - redis
#    - nodejs
#    - ruby
