---
- hosts: all
  become: true
  vars:
    user: vagrant
    home: "/home/{{ user }}"
    become_user: "{{ user }}"
  pre_tasks:
    - name: "Add repository for PHP 7.0."
      apt_repository:
        repo: "ppa:ondrej/php"
        update_cache: yes
  roles:
    - geerlingguy.git
    - dotfiles
    - mikegleasonjr.swap
    - jdauphant.nginx
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.nodejs
#    - setup
#    - nginx
#    - mysql
#    - sqlite
#    - mongo
#    - composer
#    - redis
#    - nodejs
#    - ruby
