---
- hosts: all
  become: true
  vars:
    user: vagrant
    home: "/home/{{ user }}"
    become_user: "{{ user }}"
  pre_tasks:
    - name: Add known hosts
      known_hosts:
        path: "{{ home }}/.ssh/known_hosts"
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' ~ item) }}"
      become_user: "{{ user }}"
      with_items:
        - github.com
        - bitbucket.org
  roles:
    - Stouts.apt
    - geerlingguy.git
    - dotfiles
    - mikegleasonjr.swap
    - jdauphant.nginx
    - geerlingguy.php
    - geerlingguy.composer
    - geerlingguy.nodejs
    - geerlingguy.postgresql
