
- src: Stouts.apt
  version: "1.4.0"

- src: geerlingguy.composer
  version: "1.5.0"

- src: geerlingguy.php
  version: "3.4.4"

- src: mikegleasonjr.swap
  version: "0.0.3"

- src: jdauphant.nginx
  version: "v2.7.4"

- src: geerlingguy.git
  version: "1.2.1"

- src: geerlingguy.nodejs
  version: "4.0.0"

- src: geerlingguy.postgresql
  version: "1.0.2"
