---
- name: "Install NVM"
  git: repo="https://github.com/creationix/nvm.git" dest="{{ home }}/.nvm" accept_hostkey="yes" update="yes"
  sudo: no
- name: "Install Nodejs"
  shell: source {{ home }}/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}
         executable="/bin/bash"
  sudo: no

- name: "Ensure NVM is loaded during login"
  lineinfile: dest="{{ home }}/.bashrc" line="source {{ home }}/.nvm/nvm.sh" state="present" insertafter="EOF"

- name: Install NPM packages
  shell: executable="/bin/bash" source {{ home }}/.nvm/nvm.sh && npm install -g {{ item }} chdir={{ home }}
  sudo: no
  with_items: npm_packages