---
- name: "Install NVM"
  git:
    repo: "https://github.com/creationix/nvm.git"
    dest: "{{ home }}/.nvm"
    accept_hostkey: "yes"
    update: "yes"
  become: no

- name: "Install Nodejs"
  shell: "source {{ home }}/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}"
  args:
    executable: "/bin/bash"
  become: no

- name: "Ensure NVM is loaded during login"
  lineinfile:
    dest: "{{ home }}/.bashrc"
    line: "source {{ home }}/.nvm/nvm.sh"
    state: "present"
    insertafter: "EOF"

- name: Install NPM packages
  shell: "source {{ home }}/.nvm/nvm.sh && npm install -g {{ item }} chdir={{ home }}"
  args:
    executable: "/bin/bash"
  become: no
  with_items: "{{ npm_packages }}"
