---
- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

- name: Installing Composer global packages
  sudo: no
  command: composer global require "{{ item.package }}={{ item.version }}"
  with_items: composer_packages