---
- name: Check if Composer is installed.
  stat: "path=/usr/local/bin/composer"
  register: composer_bin

- name: Download Composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: >
    php /tmp/composer-installer.php
    chdir=/tmp
  when: not composer_bin.stat.exists

- name: Move Composer into globally-accessible location.
  become: yes
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
  when: not composer_bin.stat.exists

- name: Installing Composer global packages
  become: no
  command: composer global require "{{ item.package }}={{ item.version }}"
  with_items: "{{ composer_packages }}"
