---
- name: Make Vim directory
  file:
    path: "{{ vundle_config_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Make Vim bundle directory
  file:
    path: "{{ vundle_config_dir }}/bundle"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Clone vundle
  become_user: "{{ user }}"
  git:
    repo: "{{ vundle_repo }}"
    dest: "{{ vundle_config_dir }}/bundle/Vundle.vim"
    update: no

- name: Install Vim plugins
  command: "vim +PluginInstall +qal"
