---
php_packages:
  - { name: dev, package: php5-dev }
  - { name: pear, package: php-pear }
  - { name: xdebug, package: php5-xdebug }
  - { name: curl, package: php5-curl }
  - { name: mcrypt, package: php5-mcrypt }
  - { name: mysql, package: php5-mysql }
  - { name: sqlite, package: php5-sqlite }
  - { name: redis, package: php5-redis }
  - { name: imagick, package: php5-imagick }
  - { name: intl, package: php5-intl }
  - { name: mongo, package: php5-mongo }
  - { name: gd, package: php5-gd }
  - { name: xsl, package: php5-xsl }