---
- name: Update APT
  sudo: yes
  apt:  update_cache=yes

- name: Install system packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - build-essential
    - python-software-properties

- name: Add PPA repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/php5

- name: Update APT again
  sudo: yes
  apt:  update_cache=yes

- name: Install extra packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - mcrypt