---
- name: Install PHP5-FPM
  become: yes
  apt:
    package: php5-fpm
    state: latest

- name: Install PHP5-CLI
  become: yes
  apt:
    package: php5-cli
    state: latest


# PHP Packages

- name: Install PHP packages
  become: yes
  apt:
    package: "{{ item.package }}"
    state: latest
  with_items: "{{ php_packages }}"

- name: Enable PHP packages
  become: yes
  command: /usr/sbin/php5enmod {{ item.name }} creates=/etc/php5/cli/conf.d/20-{{ item.name }}.ini
  with_items: "{{ php_packages }}"
  notify: restart php5-fpm
