---
- name: Update APT
  become: yes
  apt:  update_cache=yes

- name: Install system packages
  become: yes
  apt:  pkg="{{ item }}" state=latest
  with_items: "{{ system_packages }}"

- name: Update APT again
  become: yes
  apt:  update_cache=yes

- name: Run cachefilesd
  become: yes
  template: src=cachefilesd.j2 dest=/etc/default/cachefilesd

- name: Set locale
  become: yes
  command: "/usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}"

- name: Create Workspace directory
  become: no
  file:
    path: ~/Workspace
    state: directory
