---
- name: Update APT
  sudo: yes
  apt:  update_cache=yes

- name: Install system packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - build-essential
    - python-software-properties

- name: Add PPA repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/php5

- name: Update APT again
  sudo: yes
  apt:  update_cache=yes

- name: Install extra packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - mcrypt

- name: Copy dotfiles
  template: src={{ item }}.tpl dest={{ home_dir }}/.{{ item }}
  with_items:
    - bashrc
    - bash_aliases
    - gitconfig

- name: Set locale
  sudo: yes
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}

- name: Create Workspace directory
  sudo: no
  command: mkdir -p ~/Workspace


# swap file
- name: Create swap file
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1M count=1024
           creates="{{ swap_file_path }}"
  tags:
    - swap.file.create


- name: Change swap file permissions
  file: path="{{ swap_file_path }}"
        owner=root
        group=root
        mode=0600
  tags:
    - swap.file.permissions


- name: "Check swap file type"
  command: file {{ swap_file_path }}
  register: swapfile
  tags:
    - swap.file.mkswap


- name: Make swap file
  command: "sudo mkswap {{ swap_file_path }}"
  when: swapfile.stdout.find('swap file') == -1
  tags:
    - swap.file.mkswap


- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  tags:
    - swap.fstab


- name: Mount swap
  command: "swapon {{ swap_file_path }}"
  when: ansible_swaptotal_mb < 1
  tags:
    - swap.file.swapon