---
- name: Update APT
  sudo: yes
  apt:  update_cache=yes

- name: Install system packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - build-essential
    - python-software-properties

- name: Add PPA repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/php5

- name: Update APT again
  sudo: yes
  apt:  update_cache=yes

- name: Install extra packages
  sudo: yes
  apt:  pkg={{ item }} state=latest
  with_items: extra_packages

- name: Set locale
  sudo: yes
  command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}

- name: Create Workspace directory
  sudo: no
  command: mkdir -p ~/Workspace