- name: Install Ruby 2.0
  become: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - ruby2.0
    - ruby2.0-dev

- name: Symlink exists for Ruby 2.0
  become: yes
  file:
    src: /usr/bin/ruby2.0
    dest: /usr/local/bin/ruby
    state: link

- name: Symlink exists for Ruby Gems 2.0
  become: yes
  file:
    src: /usr/bin/gem2.0
    dest: /usr/local/bin/gem
    state: link

- name: Install Ruby gems
  become: yes
  command: "gem install {{ item }}"
  with_items: "{{ ruby_gems }}"
